# -*- coding: utf-8 -*-
"""KNN_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilm9uVn621NuM0YZCJ1K-oawRwjtCh-5
"""

from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml

# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)

#normalizing the data
X = X / 255.

# (60K: Train) and (10K: Test)
X_train, X_test = X[:60000], X[60000:]
y_train, y_test = y[:60000], y[60000:]

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np

for algo in ['ball_tree', 'brute', 'kd_tree']:
  for k in [1, 4, 5, 8, 25, 40, 17, 50, 63]:
    model = KNeighborsClassifier(n_neighbors = k, algorithm=algo)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    err = 1 - acc 
    print(f"Accuracy for {k}-nearest-neighbours using  {algo} algorithm is  : {acc}")
    print(f"Error-rate for {k}-nearest-neighbours using  {algo} algorithm is : {err}")

